# Generated by Django 3.2.3 on 2021-06-01 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_types',
            new_name='post_type',
        ),
    ]
