# Generated by Django 3.2.3 on 2021-06-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210602_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='eemail_verified',
            new_name='email_verified',
        ),
    ]
